name: CI/CD

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

permissions: {}

jobs:
  build-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: Bielov-Team-Track/devops/.github/workflows/build-frontend.yml@main
    permissions:
      contents: read
      packages: write
    with:
      push-docker-image: true
      environment: production
